# -*- coding: utf-8 -*-
"""Conways_Game_Of_Life_Shontz

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b9Kqv_klNGEObFYEBkHNbUY32TNZaHYh
"""

#Mario Shontz/MES19F
#ISC 4304C
#Due 03/03/23
#Lab 4: Conway's Game of life
    
#!/usr/bin/env/ Python3


class Config(object):
    '''Options are glider or '''
    def __init__(self,type='glider'):
        if type == 'glider':
            self.config = [[0,1,0],
                           [0,0,1],
                           [1,1,1]]
        if type == 'glider_gun':
            self.config = [[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,],
                           [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,],
                           [0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,],
                           [0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,],
                           [1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,1,],
                           [1,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,1,1,0,0,0,0,1,0,1,],
                           [0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,],
                           [0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,],
                           [0,0,0,0,0,0,0,0,0,0,0,0,1,1,]]